export const ActionsTypes = {
  GET_USERS: "GET_USERS",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
  SET_SINGLE_USER: "SET_SINGLE_USER",
  CHANGE_ACTIVE_COMPONENT: "CHANGE_ACTIVE_COMPONENT",
};
